plugins {
    id 'java'
    id 'application'
    id 'com.github.johnrengelman.shadow' version '8.0.0+'
}

mainClassName = "Main"
group 'org.example'
version '1.0'

repositories {
    mavenCentral()
    maven {
        name 'm2-dv8tion'
        url 'https://m2.dv8tion.net/releases'
    }
    maven {
        url 'https://jitpack.io'
    }
    maven {
        url "https://maven.lavalink.dev/releases"
    }
}

tasks.withType(Tar) {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
}

tasks.withType(Zip) {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
}

dependencies {
    implementation("net.dv8tion:JDA:5.0.0-beta.6")
    //implementation ('dev.arbjerg:lavaplayer:2.1.1')
    //implementation ('com.github.Nansess.lavaplayer-test:lavaplayer:19e815bd83')
    implementation ('com.github.ShimoLen:lavaplayer:1bb73fb51d')
    //implementation ("dev.lavalink.youtube:v2:1.1.0")
    //implementation("com.github.hugomjp28:lavaplayer-fork:047006a")
    //implementation("ch.qos.logback:logback-classic:1.2.8")
    implementation 'se.michaelthelin.spotify:spotify-web-api-java:6.5.4'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.7.0'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.7.0'
}

test {
    useJUnitPlatform()
}

jar {
    manifest {
        attributes "Main-Class": "Main"
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
}